### ISSUE TITLE
Python 3 Compatibility

### ISSUE THREAD

**Issue by MatTercio** [motoz/nbetest#1]
Hi:

First of all, thank you for nbetest. I am testing it in Python 2.7 and works perfectly. Now, I´m trying to use in Python 3.4 but doesn´t work. I use 2to3 script and no works still. Do you have any plan to port it. Thanks in advance.

**Comment by motoz** [comment]
Well, not any plan other than that in general I should start looking into this whole python3 thing sooner or later anyway. My main project pellmon was still held back by a library I use last I looked into it, so maybe this would be a good place to start.

Do you have a scotte V7/10? I don't, so I made this test program only from the protocol specs and with remote access to V7 box made available my NBE. Just wondering if the autodiscovery protocol works since I can't test that over the internet. It works fine with the included test server, but still would be nice to know if it works with a real controller.

**Comment by MatTercio** [comment]
Hi:
My boiler will be in mi house in 2 weeks and I think that i have v7 and v10 interfaces. Support told me that : "you need software version 7.0615 or later for it to be able to work. ". I will update with my tests.

**Comment by motoz** [comment]
Great! I added python 3 support in aea69940fcb51ec1fb17e8f706a9b1d2bbd7258d, tested with python 2.7.6 and 3.4.3
