### ISSUE TITLE
not working from NBE version x.0936 and up

### ISSUE THREAD

**Issue by hibeck** [motoz/nbetest#3]
looks like NBE have made som changes to UDP-communication again in x.0936. Do you have a fix for that? I would be very happy:-)

Thanks:-)

**Comment by motoz** [comment]
Yes, for instance the port has changed from 1900 to 8483.

I started working on a V7 plugin for pellmon https://github.com/motoz/PellMon/tree/feature/nbeprotocol/src/Pellmonsrv/plugins/nbecom/nbeprotocol (which works quite nicely now, but that's linux only). I'll try to find some time to fix nbetest later.

The protocol has grown somewhat more complicated over time, for instance writing settings is now really slow (several seconds) since the request frame must be encrypted with RSA. To avoid that a session password can be written to the controller and then a faster crypto (xtea) can be used instead, but then the xtea password needs to be stored somewhere so the client can't be completely stateless anymore. I have not really thought about what to do with the nbetest prog yet, but it's nice that you find it useful.

**Comment by motoz** [comment]
8ccc468b1fc81 works with 7.0637, but support for older versions dropped at the same time. Only RSA crypto used (no xtea) so changing settings is  slow.
